[workspace]
resolver = "2"

members = [
  # Core library
  "grid_forge_core",

  # Dimensionality implementations
  "grid_forge_2d",
  "grid_forge_3d",

  # Integration examples (commented out as per your original)
  # "example_godot/gf-rust",

    # Main facade library
  "grid_forge",
]

[workspace.package]
version = "0.2.0"
edition = "2021"
authors = ["Michał Kosiński <statismike@gmail.com>"]
description = "Grid Map abstraction library"
license = "MIT"
repository = "https://github.com/statismike/grid_forge"

[workspace.dependencies]
image = { version = "0.25.*", default-features = false }
rand = { version = "0.8.*" }

## dev-dependencies
rand_chacha = "0.3.*"
criterion = { version = "0.4", features = ["html_reports"] }

[profile.release]
debug = true