[workspace]
resolver="2"

members = [
  "grid_forge",

  # Examples:
  "examples/collapse",
  "examples/overlap",
  "examples/godot/gf-rust",
  "examples/walker",
  "examples/vis", 
  
  # Benchmarks
  "grid_forge_benches",
]
