[package]
name = "gf_gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gf_defs = { path = "../gf_defs" }

rand = { version = "^0.8.5" }
