[package]
name = "grid_forge_2d"
description = "2D rectangular tile dimension"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
bench = false

[features]
default = ['image', 'procgen']
image = ["dep:image", "grid_forge_core/image"]
procgen = ["grid_forge_core/procgen"]

[dependencies]
grid_forge_core = { path = "../grid_forge_core" }
image = { workspace = true, optional = true }

[dev-dependencies]
criterion = { workspace = true }
image = { workspace = true, features = ["png"]}

[[bench]]
name = "grid"
harness = false

[[bench]]
name = "image"
harness = false