#[macro_export]
macro_rules! __impl_singular_adjacency_rules {
    (
        struct_name: $name:ident,
        adjacency_table: $adjacency_table:ty,
        adjacencies: $adjacencies:ty,
        direction: $direction:ty,
    ) => {
        /// Adjacency rules for the singular collapse algorithm.
        #[derive(Debug)]
        pub struct $name<Data: TypedData> {
            inner: $adjacency_table,
            id_type: PhantomData<Data>,
        }

        impl<Data: TypedData> Clone for $name<Data> {
            fn clone(&self) -> Self {
                Self {
                    inner: self.inner.clone(),
                    id_type: PhantomData,
                }
            }
        }

        impl<Data: TypedData> Default for $name<Data>
        {
            fn default() -> Self {
                Self {
                    inner: <$adjacency_table>::default(),
                    id_type: PhantomData,
                }
            }
        }

        impl<Data: TypedData> $name<Data> {

            pub (crate) fn add_adjacency_raw(
                &mut self,
                tile_id: u64,
                adjacent_id: u64,
                direction: $direction,
            ) {
                self.inner.insert_adjacency(tile_id, direction, adjacent_id);
            }

            pub fn add_adjacency<Tile: AsRef<Data>>(
                &mut self,
                tile: &Tile,
                adjacent: &Tile,
                direction: $direction,
            ) {
                self.add_adjacency_raw(tile.as_ref().tile_type_id(), adjacent.as_ref().tile_type_id(), direction);
            }

            pub (crate) fn inner(&self) -> &$adjacency_table {
                &self.inner
            }

            pub fn check_adjacency(&self, tile: &Data, adjacent: &Data, direction: $direction) -> bool {
                self.inner.get_all_adjacencies_in_direction(&tile.tile_type_id(), &direction).any(|&id| id == adjacent.tile_type_id())
            }
        }
    }
}

#[macro_export]
macro_rules! __impl_singular_identity_analyzer {
    (
        struct_name: $name:ident,
        adjacency_rules: $adjacency_rules:ident,
        grid: $grid:ident,
        position: $position:ty,
        direction: $direction:ty,
    ) => {
        pub struct $name<Data: TypedData> {
            tiles: Vec<u64>,
            adjacency_rules: $adjacency_rules<Data>,
        }

        impl <Data: TypedData> Default for $name<Data> {
            fn default() -> Self {
                Self {
                    tiles: Vec::new(),
                    adjacency_rules: <$adjacency_rules<Data>>::default(),
                }
            }
        }

        impl <Data: TypedData> $name<Data> {
            fn analyze_tile_at_pos(&mut self, map: &impl $grid<Data>, pos: $position) {
                if let Some(tile) = map.get_tile_at_position(&pos) {
                    if !self.tiles.contains(&tile.as_ref().tile_type_id()) {
                        self.tiles.push(tile.as_ref().tile_type_id());
                    }
        
                    for dir in <$direction>::ALL {
                        if let Some(neighbour) = map.get_neighbour_at(&pos, &dir) {
                            self.adjacency_rules.add_adjacency(&tile, &neighbour, dir)
                        }
                    }
                }
            }

            pub fn analyze(&mut self, map: &impl $grid<Data>) {
                for position in map.get_all_positions() {
                    self.analyze_tile_at_pos(map, position);
                }
            }
        
            pub fn adjacency_rules(&self) -> &$adjacency_rules<Data> {
                &self.adjacency_rules
            }
        
            pub fn tile_type_ids(&self) -> &[u64] {
                &self.tiles
            }
        }
    }
}

#[macro_export]
macro_rules! __impl_singular_border_analyzer {
    (
        struct_name: $name:ident,
        adjacency_rules: $adjacency_rules:ident,
        direction_table: $direction_table:ident,
        grid: $grid:ident,
        position: $position:ty,
        direction: $direction:ty,
    ) => {
        /// Analyzer creating adjacency rules based on the borders between tiles.
        ///
        /// Rules generated by it are more liberal than the ones produced by [`IdentityAnalyzer`], as the tiles are deemed to be adjacent not only
        /// if they are adjacent in the sample grid, but the extra step during the process is taken - each tile border is given its unique identifier,
        /// and the tile is a viable neighbour option if their borders in given direction have the same identifier.
        ///
        /// This analyzer additionally to analyzing the map, also provides method to add the tile adjacency manually.
        pub struct $name<Data: TypedData>
        {
            tiles: Vec<u64>,
            adjacency_rules: $adjacency_rules<Data>,
            /// TileId key
            inner: TypeIdMap<$direction_table<Option<u64>>>,
            /// BorderId key; (TileId; GridDir)
            border_types: TypeIdMap<Vec<(u64, $direction)>>,
            phantom: PhantomData<Data>,
        }

        impl<Data: TypedData> Default for $name<Data>
        {
            fn default() -> Self {
                Self {
                    tiles: Vec::new(),
                    adjacency_rules: $adjacency_rules::default(),
                    inner: TypeIdMap::default(),
                    border_types: TypeIdMap::default(),
                    phantom: PhantomData,
                }
            }
        }

        impl<Data: TypedData> $name<Data> {
            pub fn analyze(&mut self, map: &impl $grid<Data>) {
                self.adjacency_rules = $adjacency_rules::default();
                for position in map.get_all_positions() {
                    self.analyze_tile_at_pos(map, position);
                }
                self.generate_adjacency_rules();
            }

            pub fn adjacency_rules(&self) -> &$adjacency_rules<Data> {
                &self.adjacency_rules
            }

            pub fn tiles(&self) -> &[u64] {
                &self.tiles
            }

            /// Manually add adjacency between two tiles.
            ///
            /// After addition of new adjacencies, the [`prepare`](Self::prepare) method should be called to generate the rules.
            pub fn add_adjacency(&mut self, tile: &Data, neighbour: &Data, direction: &$direction) {
                self.add_adjacency_raw(tile.tile_type_id(), neighbour.tile_type_id(), direction)
            }

            pub fn prepare(&mut self) {
                self.generate_adjacency_rules()
            }

            fn analyze_tile_at_pos(&mut self, map: &impl $grid<Data>, pos: $position) {
                if let Some(tile) = map.get_data_at_position(&pos) {
                    if !self.tiles.contains(&tile.tile_type_id()) {
                        self.tiles.push(tile.tile_type_id());
                    }

                    for dir in <$direction>::ALL {
                        if let Some(neighbour) = map.get_neighbour_at(&pos, &dir) {
                            self.add_adjacency_raw(
                                tile.tile_type_id(),
                                neighbour.as_ref().tile_type_id(),
                                &dir,
                            );
                        }
                    }
                }
            }

            fn generate_adjacency_rules(&mut self) {
                let border_ids = self.border_types.keys().copied().collect::<Vec<_>>();

                for border_id in border_ids.iter() {
                    let borders = self.border_types.get(border_id).unwrap().clone();

                    for half_dir in <$direction>::PRIMARY {
                        let first_borders = borders
                            .iter()
                            .filter_map(
                                |(tile, dir)| {
                                    if *dir == half_dir {
                                        Some(*tile)
                                    } else {
                                        None
                                    }
                                },
                            )
                            .collect::<Vec<_>>();
                        let second_borders = borders
                            .iter()
                            .filter_map(|(tile, dir)| {
                                if *dir == half_dir.opposite() {
                                    Some(*tile)
                                } else {
                                    None
                                }
                            })
                            .collect::<Vec<_>>();

                        for tile_first in first_borders.iter() {
                            for tile_second in second_borders.iter() {
                                self.adjacency_rules.add_adjacency_raw(
                                    *tile_first,
                                    *tile_second,
                                    half_dir,
                                );
                                self.adjacency_rules.add_adjacency_raw(
                                    *tile_second,
                                    *tile_first,
                                    half_dir.opposite(),
                                );
                            }
                        }
                    }
                }
            }

            pub(crate) fn add_adjacency_raw(&mut self, tile_id: u64, adjacent_id: u64, direction: &$direction) {
                self.ensure_adjacencies_present_for_tiles(&[tile_id, adjacent_id]);

                match (
                    self.get_border_id(&tile_id, direction),
                    self.get_border_id(&adjacent_id, &direction.opposite()),
                ) {
                    (None, None) => {
                        let new_id = self.get_next_border_id();
                        self.set_border_id(new_id, tile_id, direction);
                        self.set_border_id(new_id, adjacent_id, &direction.opposite());
                    }
                    (None, Some(id_border)) => {
                        self.set_border_id(id_border, tile_id, direction);
                    }
                    (Some(id_border), None) => {
                        self.set_border_id(id_border, adjacent_id, &direction.opposite());
                    }
                    (Some(id_left), Some(id_right)) => {
                        if id_left == id_right {
                            return;
                        }
                        self.unify_border_id(id_left.max(id_right), id_left.min(id_right));
                    }
                }
            }

            fn ensure_adjacencies_present_for_tiles(&mut self, ids: &[u64]) {
                for id in ids {
                    if !self.inner.contains_key(id) {
                        self.inner.insert(*id, $direction_table::default());
                    }
                }
            }

            fn set_border_id(&mut self, border_id: u64, tile_id: u64, direction: &$direction) {
                self.inner
                    .get_mut(&tile_id)
                    .unwrap()[*direction] = border_id.into();

                self.border_types
                    .entry(border_id)
                    .or_default()
                    .push((tile_id, *direction));
            }

            fn get_border_id(&self, tile_id: &u64, direction: &$direction) -> Option<u64> {
                self.inner.get(tile_id).unwrap()[*direction]
            }

            fn unify_border_id(&mut self, existing: u64, into: u64) {
                let cache = self.border_types.remove(&existing).unwrap();
                for (tile_id, direction) in cache.iter() {
                    self.set_border_id(into, *tile_id, direction);
                }
            }

            fn get_next_border_id(&self) -> u64 {
                if let Some(max_id) = self.border_types.keys().max() {
                    *max_id + 1
                } else {
                    0
                }
            }
        }
    }
}

#[macro_export]
macro_rules! __impl_singular_frequency_hints {
    (
        struct_name: $name:ident,
        grid: $grid:ident,
    ) => {
        /// Frequency hints for the *adjacency-based* generative algorithm.
        ///
        /// Describes the frequency of occurence of all distinct tiles. Can be generated automatically while analyzing sample
        /// maps, or specified manually for each `tile_type_id` via [`set_weight_for_tile`](Self::set_weight_for_tile) method.
        #[derive(Debug)]
        pub struct $name<Data: TypedData>
        {
            weights: BTreeMap<u64, u32>,
            id_type: PhantomData<Data>,
        }

        impl<Data: TypedData> Clone for $name<Data>
        {
            fn clone(&self) -> Self {
                Self {
                    weights: self.weights.clone(),
                    id_type: PhantomData,
                }
            }
        }

        impl<Data: TypedData> Default for $name<Data> 
        {
            fn default() -> Self {
                Self {
                    weights: BTreeMap::new(),
                    id_type: PhantomData,
                }
            }
        }

        impl<Data: TypedData> $name<Data>
        {
            pub fn set_weight_for_data<Tile>(&mut self, data: &Data, weight: u32) {
                let entry = self.weights.entry(data.tile_type_id()).or_default();
                *entry = weight;
            }

            pub fn count_data(&mut self, data: &Data) {
                if let Some(count) = self.weights.get_mut(&data.tile_type_id()) {
                    *count += 1;
                } else {
                    self.weights.insert(data.tile_type_id(), 1);
                }
            }

            pub(crate) fn get_all_weights_cloned(&self) -> BTreeMap<u64, u32> {
                self.weights.clone()
            }

            pub fn analyze(&mut self, map: &impl $grid<Data>) {
                for position in map.get_all_positions() {
                    let data = map.get_data_at_position(&position).unwrap();
                    self.count_data(&data);
                }
            }
        }

    }
}