[package]
name = "grid_forge_core"
description = "Dimensionality - independent functionality of grid_forge"
version.workspace = true  # Inherit from workspace
edition.workspace = true  # Inherit from workspace
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
bench = false

[features]
image = ["dep:image"]
procgen = ["dep:rand"]
godot = ["dep:godot"]

# Utilities for benchmarks, tests and examples
dev_utils = ["dep:rand_chacha"]

[dependencies]
image = { workspace = true, optional = true }
rand = { workspace = true, optional = true }
num-traits = "*"
grid = { version = "0.13.*" }
godot = { version = "^0.2.4", optional = true }
nohash-hasher = { workspace = true }
rand_chacha = { workspace = true, optional = true }

[dev-dependencies]
criterion = { workspace = true }
image = { workspace = true, features = ["png"]}
gif = { version ="^0.13.*" }

#[[bench]]
#name = "grid_bench"
#harness = false

#[[bench]]
#name = "vis"
#harness = false

#[[bench]]
#name = "gen_collapse_singular"
#harness = false

#[[example]]
#name = "gen_collapse_singular"
#path = "examples/collapse/gen_collapse_singular.rs"

#[[example]]
#name = "gen_walker"
#path = "examples/gen_walker.rs"

#[[example]]
#name = "vis"
#path = "examples/vis.rs"
