[package]
name = "grid_forge"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
grid_forge_core = { path = "../grid_forge_core" }
grid_forge_2d = { path = "../grid_forge_2d", optional = true }
grid_forge_3d = { path = "../grid_forge_3d", optional = true }
image = { workspace = true, optional = true, features = ["png"] }

[dev-dependencies]
rand = { workspace = true }
rand_chacha = { workspace = true }
gif = { version ="^0.13.*" }

[features]
2d = ["grid_forge_2d"]
3d = ["grid_forge_3d"]
procgen = []
image = ["grid_forge_core/image", "dep:image"]

[[example]]
name = "2d_collapse_singular"
path = "examples/2d/procgen/collapse_singular.rs"
required-features = ["2d", "procgen", "image"]

#[[example]]
#name = "3d_collapse_singular"
#path = "examples/3d/procgen/collapse_singular.rs"
#required-features = ["3d", "procgen", "image"]