[package]
name = "grid_forge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["vis", "gen"]
vis = ["dep:image"]
gen = ["dep:rand"]

[dependencies]
num-traits = "*"
image = { version = "^0.25.1", optional = true, default-features = false }
rand = { version = "^0.8.5", optional = true }

[dev-dependencies]
bencher = "*"

[[bench]]
path = "benches/walker.rs"
name = "walker"
harness = false